version: '3'

services:
  mosquitto:
    image: fstehle/rpi-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

  app:
    build: .
    depends_on:
      - mosquitto
    ports:
      - "3000:3000"
    environment:
      MQTT_HOST: mosquitto